name: pyogame
on:
  push:
    branches: [ dev ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@dev
      - name: dependecys
        uses: docker://python:3.8
        run: pip install -r requirements.txt
      - name: compile
        run: python -m py_compile ogame/__init__.py